---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci

run:
  path: ci/tasks/review-and-publish-azure-offer/run.sh

params:
  AZURE_PUBLISHER: ((AZURE_PUBLISHER))
  AZURE_OFFER: ((AZURE_OFFER))
  PARTNER_PORTAL_TENANT_ID: ((PARTNER_PORTAL_TENANT_ID))
  PARTNER_PORTAL_CLIENT_ID: ((PARTNER_PORTAL_TENANT_ID))
  PARTNER_PORTAL_CLIENT_SECRET: ((PARTNER_PORTAL_TENANT_ID))
