---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: windows-utilities-release
  - name: src/github.com/cloudfoundry-incubator/windows-utilities-tests
  - name: stemcell

run:
  path: ci/tasks/run-wuts/run

params:
  AZ:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_GW_PRIVATE_KEY:
  BOSH_GW_USER:
  BOSH_TARGET:
  IAAS:
  JUMPBOX_IP:
  JUMPBOX_PRIVATE_KEY:
  JUMPBOX_USER:
  NETWORK:
  STEMCELL_OS:
  STEMCELL_PATH:
  VM_EXTENSIONS:
  VM_TYPE:
