---
platform: windows

inputs:
- name: ci
- name: repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/run-ginkgo-exe/run.ps1

params:
  GOPATH: "repo"
  TEST_PATH: "repo"
  NODES: 4
