---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: stembuild
- name: ci

run:
  path: /bin/bash
  args:
  - -c
  - ci/tasks/stembuild/linux/contract/run.sh

params:
  GOVC_INSECURE: 1
  VCENTER_ADMIN_CREDENTIAL_URL:
  VM_FOLDER:
  PACKAGE_TEST_BASE_VM_NAME:
