---
platform: windows

inputs:
- name: stembuild
- name: ci
- name: version
- name: nimbus-ips
- name: integration-vm-name
- name: bosh-psmodules-repo

outputs:
- name: output

run:
  path: powershell
  args:
  - "-File"
  - ci/tasks/test-integration-stembuild-windows/run.ps1

params:
  VCENTER_BASE_URL:
  VCENTER_CA_CERT:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  VCENTER_ADMIN_CREDENTIAL_URL:
  VCENTER_USERNAME:
  VCENTER_PASSWORD:
  VM_USERNAME:
  VM_PASSWORD:
  VM_FOLDER:
  LOGOUT_INTEGRATION_TEST_VM_INVENTORY_PATH:
  LOGOUT_INTEGRATION_TEST_VM_IP:
  PACKAGE_TEST_BASE_VM_NAME:
  OS_LINE:
  SKIP_CLEANUP: false
