---
platform: windows

inputs:
  - name: ci
  - name: bosh-psmodules

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-Command"
  - ci/tasks/bosh-windows-stemcell-builder/bosh-psmodules/run.ps1
