---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: stemcell-builder
  - name: base-gcp-image
  - name: version
  - name: windows-stemcell-dependencies
  - name: sshd
  - name: bosh-agent-release

outputs:
  - name: bosh-windows-stemcell
  - name: hotfix-log

run:
  path: ci/tasks/bosh-windows-stemcell-builder/create-gcp-stemcell/run

params:
  ACCOUNT_JSON:
  BASE_IMAGE_DIR: ../base-gcp-image
  OS_VERSION: windows2012R2
  VERSION_DIR: ../version
  STEMCELL_DEPS_DIR: ../windows-stemcell-dependencies
  VM_PREFIX:
  BOSH_AGENT_DIR: bosh-agent-release
