---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: stembuild
  - name: ci
  - name: stembuild-version
  - name: stemcell-automation-release
    optional: true
  - name: zip-file
    optional: true

outputs:
  - name: output

params:
  STEMCELL_AUTOMATION_ZIP:

run:
  path: /bin/bash
  args:
    - -c
    - ci/tasks/build-stembuild-linux/run.sh