---
platform: windows

inputs:
- name: stembuild
- name: ci
- name: stembuild-version
- name: stemcell-automation-release

outputs:
- name: output

params:
  STEMCELL_AUTOMATION_ZIP:

run:
  path: powershell
  args:
  - "-File"
  - ci/tasks/build-stembuild-windows/run.ps1
