---
platform: windows

inputs:
  - name: ci
  - name: version
  - name: stemcell-builder
  - name: stemcell-builder-release
  - name: windows-stemcell-dependencies
  - name: sshd

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/bosh-windows-stemcell-builder/create-vsphere-patchfile/run.ps1
params:
  ADMINISTRATOR_PASSWORD:
  AWS_ACCESS_KEY_ID:
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY:
  AZURE_CONTAINER_NAME:
  AZURE_STORAGE_ACCESS_KEY:
  AZURE_STORAGE_ACCOUNT_NAME:
  CACHE_DIR:
  ORGANIZATION:
  OS_VERSION: windows2012R2
  OUTPUT_DIR: ../bosh-windows-stemcell/packer-output
  OWNER:
  PRODUCT_KEY:
  STEMCELL_DEPS_DIR:
  UPDATES_HTTPS_PROXY:
  UPDATES_HTTP_PROXY:
  UPDATES_PROXY_BYPASS_LIST:
  VERSION_DIR: ../version
  VHD_VMDK_BUCKET:

outputs:
  - name: patchfile-manifest
  - name: manifest