---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: stemcell-builder
  - name: base-gcp-image
  - name: version
  - name: windows-stemcell-dependencies
  - name: sshd
  - name: bosh-windows-stemcell

outputs:
  - name: untested-stemcell

run:
  path: ci/tasks/bosh-windows-stemcell-builder/publish-gcp-stemcell/run

params:
  OS_VERSION:
  ACCOUNT_JSON:

  VERSION_DIR: ../version
  BASE_IMAGE_DIR: ../base-gcp-image
