---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: bosh-deployment
  - name: ci
  - name: jumpbox-deployment
  - name: greenhouse-private

outputs:
  - name: updated-greenhouse-private

run:
  path: ci/tasks/run-bbl/run.sh

params:
  GIT_COMMIT_EMAIL: "bosh-windows-eng@pivotal.io"
  GIT_COMMIT_USERNAME: "CI Bot"
  GIT_COMMIT_MESSAGE: "Update bbl state dir"
  SWAN_ACCOUNT_JSON:
  BBL_GCP_REGION:
  BBL_IAAS:
  BBL_ENV_NAME:
