---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
  - name: bosh-deployment
  - name: ci
  - name: jumpbox-deployment
  - name: greenhouse-private

outputs:
  - name: updated-greenhouse-private

run:
  path: ci/tasks/run-bbl/run.sh

params:
  BBL_GCP_SERVICE_ACCOUNT_KEY:
  BBL_GCP_REGION:
  BBL_IAAS:
  BBL_ENV_NAME: