---
platform: windows

inputs:
  - name: ci
  - name: stembuild-untested-windows

outputs:
  - name: stembuild-built-stemcell

run:
  path: powershell
  args:
    - "-File"
    - ci/tasks/test-stembuild-windows-stemcell/stembuild-package/run.ps1

params:
  VCENTER_BASE_URL:
  VCENTER_CA_CERT:
  VCENTER_USERNAME:
  VCENTER_PASSWORD:
  STEMBUILD_BASE_VM_NAME:
  VCENTER_VM_FOLDER:
