---
platform: windows

inputs:
  - name: ci
  - name: version
  - name: stemcell-builder
  - name: windows-stemcell-dependencies
  - name: bosh-psmodules-repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/bosh-windows-stemcell-builder/create-vmx-add-updates/run.ps1

params:
  ADMINISTRATOR_PASSWORD: replace-me
  AWS_ACCESS_KEY_ID:
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY:
  INPUT_BUCKET:
  OS_VERSION: "windows2012R2"
  OUTPUT_BUCKET:
  UPDATES_HTTPS_PROXY:
  UPDATES_HTTP_PROXY:
  UPDATES_PROXY_BYPASS_LIST:
  VERSION_DIR: ../version
  VMX_CACHE_DIR: "C:\\vmx-data"
  BOSH_PSMODULES_DIR: "../bosh-psmodules-repo"
