---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci
- name: source-repo

outputs:
- name: bumped-repo

run:
  path: ci/tasks/bump-submodules/run
