---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
  - name: ci
  - name: stembuild-untested-windows
  - name: stembuild-untested-linux
  - name: pivnet-old-release
outputs:
  - name: pivnet-new-release
run:
  path: ci/tasks/stembuild-pivnet/prepare-folder/run.sh
params:
  OS_NAME:

