---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci

run:
  path: ci/tasks/bosh-deld/run

params:
  BOSH_DEPLOYMENT: cf
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
