---
platform: windows

inputs:
  - name: ci
  - name: version
  - name: vmx-version
  - name: stemcell-builder
  - name: windows-stemcell-dependencies
  - name: sshd
  - name: stembuild

outputs:
  - name: hotfix-log

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/bosh-windows-stemcell-builder/create-vsphere-stemcell-from-vmx/run.ps1
params:
  ADMINISTRATOR_PASSWORD: replace-me
  AWS_ACCESS_KEY_ID:
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY:
  ENABLE_RDP:
  INPUT_BUCKET:
  NEW_PASSWORD:
  ORGANIZATION:
  OS_VERSION: windows2012R2
  OUTPUT_BUCKET:
  OWNER:
  PRODUCT_KEY:
  SKIP_WINDOWS_UPDATE: false
  STEMCELL_DEPS_DIR: ../windows-stemcell-dependencies
  UPDATES_HTTPS_PROXY:
  UPDATES_HTTP_PROXY:
  UPDATES_PROXY_BYPASS_LIST:
  VERSION_DIR: ../version
  VMX_CACHE_DIR: "C:\\var\\vcap\\data\\vmx-data"
  VMX_VERSION_DIR: ../vmx-version
