---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
  - name: ci
  - name: source-folder
  - name: pivnet-release
  - name: version
outputs:
  - name: pivnet-metadata
run:
  path: ci/tasks/pivnet-upload/run

