---
platform: windows

inputs:
  - name: librsync
  - name: stembuild
  - name: ci
  - name: stembuild-version

run:
  path: powershell
  args:
    - "-File"
    - ci/tasks/stembuild/windows/unit/run.ps1
