---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: stembuild
  - name: ci
  - name: version
  - name: ovftool

run:
  path: /bin/bash
  args:
    - -c
    - ci/tasks/test-units-stembuild-linux/run.sh
