---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby-bosh-cli}}

inputs:
  - name: release
  - name: ci
  - name: version

outputs:
 - name: garden-windows-output

run:
  path: ci/tasks/create-release/run
