---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci
- name: stembuild-untested-windows
- name: stembuild-untested-linux
- name: stembuild-version

outputs:
- name: output

run:
  path: ci/tasks/set-stembuild-version/run.sh
