---
platform: windows

inputs:
- name: librsync
- name: stembuild
- name: ci
- name: stembuild-version

outputs:
- name: output

run:
  path: powershell
  args:
  - "-File"
  - ci/tasks/build-stembuild-windows/run.ps1
