---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: repo
  - name: s3-bucket

outputs:
  - name: updated_repo

run:
  path: ci/tasks/update-tar/run

params:
  TAR_PATHS:
