---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/govc}}

inputs:
- name: ci
- name: vcenter-ips

run:
  path: ci/tasks/setup-integration-test-vm/run.sh

params:
  VCENTER_ADMIN_CREDENTIAL_URL:
  OS_LINE:
  BASE_VM_IPATH: /pizza-boxes-dc/vm/bloodmyst/base
  CLONE_DATASTORE:
  CLONE_RESOURCE_POOL:
  VM_CUSTOMIZATION_NAME: Bosh-Windows-Base
  CLONE_FOLDER: /pizza-boxes-dc/vm/bloodmyst
