---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: stembuild
- name: ci

run:
  path: ci/tasks/test-contract-stembuild-linux/run.sh

params:
  GOVC_INSECURE: 1
  VCENTER_ADMIN_CREDENTIAL_URL:
  VM_FOLDER:
  PACKAGE_TEST_BASE_VM_NAME:
  VCENTER_URL:
  VCENTER_USERNAME:
  VCENTER_PASSWORD:
  VCENTER_CA_CERT:
  CONTRACT_TEST_VM_PATH:
  CONTRACT_TEST_VM_PASSWORD:
  CONTRACT_TEST_VM_USERNAME: