resources:
  - name: ci
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
  - name: cf-deployment-concourse-tasks
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
      tag_filter: v3.*
  - name: bosh-deployment
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      tag_filter: v3.*
  - name: greenhouse-private
    type: git
    source:
      branch: master
      uri: git@github.com:pivotal-cf/greenhouse-private.git
      private_key: ((GREENHOUSE_PRIVATE_DEPLOY_KEY))

jobs:
  - name: create-gcp-test #interpolate ((BBL_ENV_NAME))
    plan:
      - in_parallel:
          - get: ci
          - get: cf-deployment-concourse-tasks
          - get: bosh-deployment
          - get: bbl-state
            resource: greenhouse-private
      - task: update-bosh-deployment
        file: ci/tasks/update-bbl-env-bosh-deployment/task.yml
        params:
          GIT_COMMIT_EMAIL: "bosh-windows-eng@pivotal.io"
          GIT_COMMIT_USERNAME: "CI Bot"
      - task: bbl-up
        file: cf-deployment-concourse-tasks/bbl-up/task.yml
        input_mapping: { bbl-config: bbl-state, bbl-state: bbl-state-with-updated-bosh-deployment }
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((GCP_SERVICE_ACCOUNT_KEY))
          # - Key content or path to the file containing credentials downloaded from GCP
          # - Path is relative to the `bbl-state` input
          BBL_GCP_REGION: ((GCP_REGION))
          BBL_STATE_DIR: dev-envs/((BBL_ENV_NAME))
          BBL_IAAS: gcp
          BBL_ENV_NAME: ((BBL_ENV_NAME))
          GIT_COMMIT_EMAIL: "bosh-windows-eng@pivotal.io"
          GIT_COMMIT_USERNAME: "CI Bot"
          GIT_COMMIT_MESSAGE: "Update bbl state dir"
          SKIP_LB_CREATION: true

      - put: updated-bbl-state
        params: {repository: greenhouse-private }
