resources:
  - name: ci
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
  - name: bosh-deployment
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/bosh-deployment.git
  - name: jumpbox-deployment
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/jumpbox-deployment.git
  - name: greenhouse-private
    type: git
    source:
      branch: master
      uri: git@github.com:pivotal-cf/greenhouse-private.git
      private_key: ((GREENHOUSE_PRIVATE_DEPLOY_KEY))

jobs:
  - name: create-gcp-test #interpolate ((BBL_ENV_NAME))
    plan:
      - in_parallel:
          - get: ci
          - get: bosh-deployment
          - get: jumpbox-deployment
          - get: greenhouse-private

      - task: run-bbl
        file: ci/tasks/run-bbl/task.yml
        params:
          SWAN_ACCOUNT_JSON: ((SWAN_ACCOUNT_JSON))
          BBL_GCP_REGION: us-east1
          BBL_IAAS: gcp
          BBL_ENV_NAME: gcp-test
      - put: greenhouse-private
        params:
          repository: updated-greenhouse-private
          rebase: true
  - name: create-aws-test
    plan:
      - in_parallel:
          - get: ci
          - get: bosh-deployment
          - get: jumpbox-deployment
          - get: greenhouse-private
      - task: run-bbl-aws
        file: ci/tasks/run-bbl/task.yml
        params:
          BBL_AWS_ACCESS_KEY_ID: ((access_key_id))
          BBL_AWS_SECRET_ACCESS_KEY: ((secret_access_key))
          BBL_AWS_REGION: us-east-1
          BBL_IAAS: aws
          BBL_ENV_NAME: aws-test
      - put: greenhouse-private
        params:
          repository: updated-greenhouse-private
          rebase: true

  - name: create-azure-test
    plan:
    - in_parallel:
      - get: ci
      - get: bosh-deployment
      - get: jumpbox-deployment
      - get: greenhouse-private
    - task: run-bbl-azure
      file: ci/tasks/run-bbl/task.yml
      params:
        BBL_IAAS: azure
#        AZURE_DEV_JSON: ((AZURE_DEV_JSON))
        BBL_AZURE_CLIENT_ID:
        BBL_AZURE_CLIENT_SECRET:
        BBL_AZURE_REGION:
        BBL_AZURE_SUBSCRIPTION_ID:
        BBL_AZURE_TENANT_ID:
        BBL_ENV_NAME: azure-test
    - put: greenhouse-private
      params:
        repository: updated-greenhouse-private
        rebase: true
