resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: concourse-windows-release
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf-experimental/concourse-windows-worker-release.git
    private_key: {{CONCOURSE_WINDOWS_DEPLOY_KEY}}
- name: concourse-windows-release-github-release
  type: github-release
  source:
    user: pivotal-cf-experimental
    repository: concourse-windows-worker-release
    pre_release: true
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}
- name: concourse-github-release
  type: github-release
  source:
    user: concourse
    repository: concourse

jobs:
- name: bump-concourse-windows-release
  plan:
  - aggregate:
    - get: ci
    - get: concourse-github-release
      trigger: true
      params:
        globs:
          - concourse_windows_amd64.exe
    - get: concourse-windows-release
  - task: bump-concourse-windows-release
    file: ci/tasks/bump-concourse-windows-release/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: concourse-windows-release
    params:
      repository: concourse-windows-release-out
      tag: concourse-github-release/version
      rebase: true
  - put: concourse-windows-release-github-release
    params:
      name: concourse-github-release/version
      tag: concourse-github-release/version
      body: body/body.txt
      globs:
        - concourse-windows-tarball/concourse-windows-worker-*.tgz
