resources:
# dockerfiles

- name: ci-pivnet-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.pivnet ]

- name: ci-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.ci ]

- name: govc-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.govc ]

# docker build resources

- name: pivnet-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/pivnet
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

- name: ci-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

- name: govc-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

jobs:
- name: build-and-push-pivnet
  plan:
  - get: ci-pivnet-dockerfile
    trigger: true
  - put: pivnet-image
    params:
      build: ci-pivnet-dockerfile/docker
      dockerfile: ci-pivnet-dockerfile/docker/Dockerfile.pivnet
      tag_as_latest: true

- name: build-and-push-ci
  plan:
  - get: ci-dockerfile
    trigger: true
  - put: ci-image
    params:
      build: ci-dockerfile/docker
      dockerfile: ci-dockerfile/docker/Dockerfile.ci
      tag_as_latest: true

- name: build-and-push-govc
  plan:
    - get: govc-dockerfile
      trigger: true
    - put: govc-image
      params:
        build: govc-dockerfile/docker
        dockerfile: govc-dockerfile/docker/Dockerfile.govc
        tag_as_latest: true
