resources:
#- name: ci
#  type: git
#  source:
#    branch: master
#    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

- name: stemcell-automation
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-automation.git

- name: pester
  type: git
  source:
    branch: master
    uri: https://github.com/pester/Pester.git
    tag_filter: 4.4.0

- name: open-ssh
  type: github-release
  source:
    owner: PowerShell
    repository: Win32-OpenSSH

- name: bosh-windows-stemcell-builder
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-windows-stemcell-builder

- name: lgpo
  type: s3
  source:
    bucket: all-bosh-windows
    regexp: external-dependencies/lgpo/LGPO-(.*).zip
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))


jobs:
- name: unit-test
  serial: true
  plan:
  - aggregate:
    - get: stemcell-automation
      trigger: true
#    - get: ci
    - get: pester
  - task: test-stemcell-automation
    config:
      platform: windows
      inputs:
      - name: stemcell-automation
      - name: pester
      run:
        path: powershell
        args:
        - "-Command"
        - "& {
              Import-Module ./Pester/pester.psm1;
              pushd stemcell-automation;
              $result=Invoke-Pester -PassThru;
              popd;
              Write-Host \"Failed Tests:\"$result.FailedCount;
              exit $result.FailedCount
            }"

- name: package
  serial: true
  plan:
  - aggregate:
    - get: stemcell-automation
      passed: [ unit-test ]
    - get: open-ssh
      version: { tag: ((OPEN_SSH_VERSION)) }
    - get: stemcell-builder
      resource: bosh-windows-stemcell-builder
    - get: lgpo
#    - get: ci
  - task: generate-deps-file
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}
      inputs:
      - name: stemcell-automation
      - name: open-ssh
      - name: stemcell-builder
      - name: lgpo
      run:
        path: /bin/bash
        args:
          - -c
          - |
            cp ./open-ssh/OpenSSH-Win64.zip ./stemcell-automation
            cp ./stemcell-builder/bosh-psmodules.zip ./stemcell-automation
            cp ./stemcell-builder/agent.zip ./stemcell-automation
            cp ./lgpo/LGPO-*.zip ./stemcell-automation/LGPO.zip
            pushd ./stemcell-automation
            ./mk-deps.sh
            cat deps.json




#- name: post-draft-release
