groups:
- name: all
  jobs:
  - build
  - build-stembuild-windows
  - build-stembuild-linux
  - post-draft-release

resources:
#repos
- name: librsync-windows
  type: git
  source:
    branch: mingw64-fseeko64-v2.0.0-windows
    uri: https://github.com/charlievieth/librsync.git

- name: librsync-linux
  type: git
  source:
    branch: mingw64-fseeko64-v2.0.0
    uri: https://github.com/charlievieth/librsync.git

- name: stembuild
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/stembuild.git

- name: ci
  type: git
  source:
    branch: ((CI_BRANCH))
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

#releases
- name: stembuild-release
  type: github-release
  source:
    owner: pivotal-cf-experimental
    repository: stembuild
    pre_release: true
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
    drafts: true

#files
- name: stembuild-untested-windows
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/untested/stembuild-windows-x86_64-(.*).exe
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

- name: stembuild-untested-linux
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/untested/stembuild-linux-x86_64-(.*)
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

- name: ovftool
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/dependencies/VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

#versions
- name: stembuild-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: stembuild/version
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "0.14.0"

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: stembuild
      trigger: true
    - get: stembuild-version
  - put: stembuild-version
    params: {bump: patch}

- name: build-stembuild-windows
  serial: true
  plan:
  - aggregate:
    - get: librsync
      resource: librsync-windows
    - get: stembuild
      passed: [ build ]
    - get: ci
    - get: stembuild-version
      passed: [ build ]
      trigger: true
  - task: build
    tags: [vsphere-stembuild-worker]
    file: ci/build-stembuild-windows/task.yml
  - put: stembuild-untested-windows
    params:
      file: output/stembuild-windows-x86_64-*.exe

- name: build-stembuild-linux
  serial: true
  plan:
  - aggregate:
    - get: librsync
      resource: librsync-linux
    - get: stembuild
      passed: [ build ]
    - get: ci
    - get: stembuild-version
      passed: [ build ]
      trigger: true
    - get: ovftool
  - task: build
    file: ci/build-stembuild-linux/task.yml
  - put: stembuild-untested-linux
    params:
      file: output/stembuild-linux-x86_64-*

- name: post-draft-release
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: stembuild-untested-windows
      passed: [ build-stembuild-windows ]
    - get: stembuild-untested-linux
      passed: [ build-stembuild-linux ]
    - get: stembuild-version
      passed: [ build-stembuild-linux, build-stembuild-windows ]
  - task: trim-version-from-binaries
    file: ci/set-stembuild-version/task.yml
  - put: stembuild-release
    params:
      name: output/tag
      tag: output/tag
      globs:
      - output/stembuild-*-x86_64-*
  - put: stembuild-version
    params: {bump: minor}
