groups:
- name: all
  jobs:
  - create-vsphere-add-updates
  - test-stemcell-builder
  - test-bosh-psmodules
  - build-event-log-release
- name: stemcell-builder
  jobs:
  - test-stemcell-builder
- name: bosh-psmodules
  jobs:
  - test-bosh-psmodules
- name: event-log-release
  jobs:
  - build-event-log-release

resource_types:
- name: metalink-repository
  type: registry-image
  source:
    repository: dpb587/metalink-repository-resource

resources:
# repos
- name: ci
  type: git
  source:
    branch: ((CI_BRANCH))
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

- name: stemcell-builder-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))

- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))

- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: ((PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY))

- name: event-log-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/event-log-release.git
    private_key: ((EVENT_LOG_RELEASE_DEPLOY_KEY))

- name: bosh-psmodules-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-psmodules.git

#releases

- name: bosh-agent-release
  type: metalink-repository
  source:
    uri: git+https://github.com/cloudfoundry/bosh-agent-index.git//
    version: ((BOSH_AGENT_RELEASE_VERSION))

- name: event-log-release-github
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: event-log-release
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
    drafts: true

# time
- name: monthly-updates-trigger
  type: time
  source:
    interval: 720h

# locks
- name: vsphere-worker-lock
  type: pool
  source:
    branch: master
    pool: 'vsphere-worker-lock'
    private_key: ((BOSH-WINDOWS-LOCKS-CI_KEY))
    uri: git@github.com:pivotal-cf-experimental/Bosh-Windows-Locks

- name: updated-vmx-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: 2012R2/versions/vsphere-updated-vmx
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "1.0.0"

- name: event-log-release-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: event-log-release/version
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "0.2.0"
- name: test-psmodules-lock
  type: pool
  source:
    branch: master
    pool: "test-psmodules"
    private_key: ((BOSH-WINDOWS-LOCKS-CI_KEY))
    uri: git@github.com:pivotal-cf-experimental/Bosh-Windows-Locks

jobs:
- name: create-vsphere-add-updates
  serial: true
  plan:
  - put: vsphere-worker-lock
    params:
      acquire: true
  - do:
    - in_parallel:
        fail_fast: true
        steps:
        - get: monthly-updates-trigger
          trigger: true
        - get: ci
        - get: stemcell-builder
        - get: windows-stemcell-dependencies
        - get: vmx-version
          resource: updated-vmx-version
        - get: bosh-psmodules-repo
          passed: [test-bosh-psmodules]
    - task: add-updates
      privileged: true
      input_mapping: { version: vmx-version }
      file: ci/tasks/create-vmx-add-updates/task.yml
      tags: [vsphere-windows-worker]
      params:
        ADMINISTRATOR_PASSWORD: "Password123!"
        AWS_ACCESS_KEY_ID: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
        AWS_REGION: us-east-1
        INPUT_BUCKET: "all-bosh-windows/2012R2/untested/vsphere/internal/inputs"
        OUTPUT_BUCKET: "all-bosh-windows/2012R2/untested/vsphere/internal/inputs"
    - put: updated-vmx-version
      params: {bump: major}
    ensure:
      put: vsphere-worker-lock
      params:
        release: vsphere-worker-lock

- name: test-stemcell-builder
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: stemcell-builder-develop
        trigger: true
      - get: stemcell-builder-master
        resource: stemcell-builder
      - get: bosh-agent-release
      - get: bosh-psmodules-repo
        passed: [test-bosh-psmodules]
  - task: test-stemcell-builder
    file: ci/tasks/test-stemcell-builder/task.yml
    input_mapping: {stemcell-builder: stemcell-builder-develop}
  - task: merge-to-master
    input_mapping: { from-repo: stemcell-builder-develop, to-repo: stemcell-builder-master }
    file: ci/tasks/merge-repo/task.yml
    params:
      FROM_BRANCH: develop
  - put: stemcell-builder
    params: { repository: merged-repo/to-repo }

- name: test-bosh-psmodules
  serial: true
  plan:
  - put: test-psmodules-lock
    params:
      acquire: true
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: bosh-psmodules-repo
  - task: test-units-bosh-psmodules
    file: ci/tasks/test-units-bosh-psmodules/task.yml
    input_mapping: {bosh-psmodules: bosh-psmodules-repo}
    tags:
      - vsphere-stembuild-worker
  ensure:
    put: test-psmodules-lock
    params:
      release: test-psmodules-lock

- name: build-event-log-release
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: event-log-release-version
        params:
          bump: minor
      - get: event-log-release
  - task: finalize-release
    file: ci/tasks/finalize-release/task.yml
    input_mapping:
      release: event-log-release
      version: event-log-release-version
    params:
      RELEASE_NAME: event-log
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: event-log-release
    params:
      repository: finalized-release/release
      tag: event-log-release-version/number
  - put: event-log-release-version
    params:
      file: event-log-release-version/number
  - put: event-log-release-github
    params:
      name: event-log-release-version/number
      tag: event-log-release-version/number
      globs:
      - finalized-release/event-log-*.tgz
