groups:
- name: all
  jobs:
  - test-bosh-psmodules
  - build-event-log-release
- name: bosh-psmodules
  jobs:
  - test-bosh-psmodules
- name: event-log-release
  jobs:
  - build-event-log-release

resource_types:
- name: metalink-repository
  type: registry-image
  source:
    repository: dpb587/metalink-repository-resource

resources:
# repos
- name: ci
  type: git
  source:
    branch: ((CI_BRANCH))
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

- name: event-log-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/event-log-release.git
    private_key: ((EVENT_LOG_RELEASE_DEPLOY_KEY))

- name: bosh-psmodules-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-psmodules.git

#releases
- name: event-log-release-github
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: event-log-release
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
    drafts: true

- name: event-log-release-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: event-log-release/version
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "0.2.0"

# locks
- name: test-psmodules-lock
  type: pool
  source:
    branch: master
    pool: "test-psmodules"
    private_key: ((BOSH-WINDOWS-LOCKS-CI_KEY))
    uri: git@github.com:pivotal-cf-experimental/Bosh-Windows-Locks

jobs:
- name: test-bosh-psmodules
  serial: true
  plan:
  - put: test-psmodules-lock
    params:
      acquire: true
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: bosh-psmodules-repo
  - task: test-units-bosh-psmodules
    file: ci/tasks/test-units-bosh-psmodules/task.yml
    input_mapping: {bosh-psmodules: bosh-psmodules-repo}
    tags:
      - vsphere-stembuild-worker
  ensure:
    put: test-psmodules-lock
    params:
      release: test-psmodules-lock

- name: build-event-log-release
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: event-log-release-version
        params:
          bump: minor
      - get: event-log-release
  - task: finalize-release
    file: ci/tasks/finalize-release/task.yml
    input_mapping:
      release: event-log-release
      version: event-log-release-version
    params:
      RELEASE_NAME: event-log
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: event-log-release
    params:
      repository: finalized-release/release
      tag: event-log-release-version/number
  - put: event-log-release-version
    params:
      file: event-log-release-version/number
  - put: event-log-release-github
    params:
      name: event-log-release-version/number
      tag: event-log-release-version/number
      globs:
      - finalized-release/event-log-*.tgz
