groups:
- name: all
  jobs:
  - build
  - build-stembuild-windows
  - build-stembuild-linux
  - bump-stemcell-builder-submodules
  - create-vsphere-add-updates
  - post-draft-release
  - test-stemcell-builder
  - build-draft-event-log-release
  - build-final-event-log-release
- name: stembuild
  jobs:
  - build
  - build-stembuild-windows
  - build-stembuild-linux
  - post-draft-release
- name: stemcell-builder
  jobs:
  - bump-stemcell-builder-submodules
  - test-stemcell-builder
- name: event-log-release
  jobs:
  - build-draft-event-log-release
  - build-final-event-log-release

resources:
# repos
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent.git

- name: bwats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests.git

- name: ci
  type: git
  source:
    branch: ((CI_BRANCH))
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

- name: librsync
  type: git
  source:
    branch: master
    uri: https://github.com/librsync/librsync.git
    tag_filter: v*

- name: stembuild
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/stembuild.git

- name: stemcell-builder-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))

- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))

- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: ((PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY))

- name: event-log-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/event-log-release.git

#releases
- name: stembuild-release
  type: github-release
  source:
    owner: pivotal-cf-experimental
    repository: stembuild
    pre_release: true
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
    drafts: true

- name: event-log-release-github-draft
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: event-log-release
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
    drafts: true

- name: event-log-release-github
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: event-log-release
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))

# time
- name: monthly-updates-trigger
  type: time
  source:
    interval: 720h

#files
- name: stembuild-untested-windows
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/untested/stembuild-windows-x86_64-(.*).exe
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

- name: stembuild-untested-linux
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/untested/stembuild-linux-x86_64-(.*)
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

- name: ovftool
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/dependencies/VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

# locks
- name: vsphere-worker-lock
  type: pool
  source:
    branch: master
    pool: 'vsphere-worker-lock'
    private_key: ((BOSH-WINDOWS-LOCKS-CI_KEY))
    uri: git@github.com:pivotal-cf-experimental/Bosh-Windows-Locks

# versions
- name: stembuild-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: stembuild/version
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "0.14.0"

- name: updated-vmx-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: 2012R2/versions/vsphere-updated-vmx
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "1.0.0"

- name: event-log-release-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: event-log-release/version
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "0.2.0"


jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: stembuild
      trigger: true
    - get: stembuild-version
  - put: stembuild-version
    params: {bump: patch}

- name: build-stembuild-windows
  serial: true
  plan:
  - aggregate:
    - get: librsync
    - get: stembuild
      passed: [ build ]
    - get: ci
    - get: stembuild-version
      passed: [ build ]
      trigger: true
  - task: build
    tags: [vsphere-stembuild-worker]
    file: ci/tasks/build-stembuild-windows/task.yml
  - put: stembuild-untested-windows
    params:
      file: output/stembuild-windows-x86_64-*.exe

- name: build-stembuild-linux
  serial: true
  plan:
  - aggregate:
    - get: librsync
    - get: stembuild
      passed: [ build ]
    - get: ci
    - get: stembuild-version
      passed: [ build ]
      trigger: true
    - get: ovftool
  - task: build
    file: ci/tasks/build-stembuild-linux/task.yml
  - put: stembuild-untested-linux
    params:
      file: output/stembuild-linux-x86_64-*

- name: bump-stemcell-builder-submodules
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder-develop
    - get: bosh-agent
      trigger: true
    - get: bwats
      trigger: true
  - task: bump-submodules
    input_mapping:
      source-repo: stemcell-builder-develop
    output_mapping:
      bumped-repo: stemcell-builder-bumped
    file: ci/tasks/bump-submodules/task.yml
  - put: stemcell-builder-develop
    params:
      repository: stemcell-builder-bumped
      rebase: true

- name: create-vsphere-add-updates
  serial: true
  plan:
  - put: vsphere-worker-lock
    params:
      acquire: true
  - do:
    - aggregate:
      - get: monthly-updates-trigger
        trigger: true
      - get: ci
      - get: stemcell-builder
      - get: windows-stemcell-dependencies
      - get: vmx-version
        resource: updated-vmx-version
    - task: add-updates
      privileged: true
      input_mapping: { version: vmx-version }
      file: ci/tasks/bosh-windows-stemcell-builder/create-vmx-add-updates/task.yml
      tags: [vsphere-windows-worker]
      params:
        OS_VERSION: windows2012R2
        ADMINISTRATOR_PASSWORD: "Password123!"
        AWS_ACCESS_KEY_ID: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
        AWS_REGION: us-east-1
        INPUT_BUCKET: "all-bosh-windows/2012R2/untested/vsphere/internal/inputs"
        OUTPUT_BUCKET: "all-bosh-windows/2012R2/untested/vsphere/internal/inputs"
    - put: updated-vmx-version
      params: {bump: major}
    ensure:
      put: vsphere-worker-lock
      params:
        release: vsphere-worker-lock

- name: post-draft-release
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: stembuild-untested-windows
      passed: [ build-stembuild-windows ]
    - get: stembuild-untested-linux
      passed: [ build-stembuild-linux ]
    - get: stembuild-version
      passed: [ build-stembuild-linux, build-stembuild-windows ]
  - task: trim-version-from-binaries
    file: ci/tasks/set-stembuild-version/task.yml
  - put: stembuild-release
    params:
      name: output/tag
      tag: output/tag
      globs:
      - output/stembuild-*-x86_64-*
  - put: stembuild-version
    params: {bump: minor}

- name: test-stemcell-builder
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder-develop
      trigger: true
    - get: stemcell-builder-master
      resource: stemcell-builder
  - aggregate:
    - task: test-stemcell-builder
      file: ci/tasks/bosh-windows-stemcell-builder/rspec/task.yml
      input_mapping: {stemcell-builder: stemcell-builder-develop}
    - task: test-bosh-psmodules
      file: ci/tasks/bosh-windows-stemcell-builder/bosh-psmodules/task.yml
      input_mapping: {stemcell-builder: stemcell-builder-develop}
  - task: merge-to-master
    input_mapping: { from-repo: stemcell-builder-develop, to-repo: stemcell-builder-master }
    file: ci/tasks/merge-repo/task.yml
    params:
      FROM_BRANCH: develop
  - put: stemcell-builder
    params: { repository: merged-repo/to-repo }

- name: build-draft-event-log-release
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: event-log-release-version
      params:
        bump: minor
    - get: event-log-release
      trigger: true
  - task: create-dev-release
    input_mapping:
      version: event-log-release-version
      release: event-log-release
    file: ci/tasks/bosh-cr/task.yml
  - put: event-log-release-github-draft
    params:
      name:
      tag: event-log-release-version/number
      name: event-log-release-version/number
      globs:
      - release-tarball/*.tgz

- name: build-final-event-log-release
  serial: true
  plan:
  - aggregate:
      - get: ci
      - get: event-log-release-version
        params:
          bump: minor
      - get: event-log-release
        passed: [ build-draft-event-log-release ]
  - task: finalize-release
    file: ci/tasks/finalize-release/task.yml
    input_mapping:
      release: event-log-release
      version: event-log-release-version
    params:
      RELEASE_NAME: event-log-release
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: event-log-release
    params:
      repository: finalized-release/release
      tag: event-log-release-version/number
  - put: event-log-release-version
    params:
      file: event-log-release-version/number
  - put: event-log-release-github
    params:
      name: event-log-release-version/number
      tag: event-log-release-version/number
      globs:
      - finalized-release/event-log-release-*.tgz
