groups:
- name: all
  jobs:
  - build-stempatch
  - build-stempatch-windows
  - build-stempatch-linux
  - bump-stemcell-builder-submodules
  - create-vsphere-add-updates
  - post-stempatch-draft-release
  - test-stemcell-builder
  - build-event-log-release
- name: stempatch
  jobs:
  - build-stempatch-windows
  - build-stempatch-linux
  - post-stempatch-draft-release
- name: stemcell-builder
  jobs:
  - bump-stemcell-builder-submodules
  - test-stemcell-builder
- name: event-log-release
  jobs:
  - build-event-log-release

resources:
# repos
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent.git

- name: bwats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests.git

- name: ci
  type: git
  source:
    branch: ((CI_BRANCH))
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

- name: librsync
  type: git
  source:
    branch: master
    uri: https://github.com/librsync/librsync.git
    tag_filter: v*

- name: stempatch
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/stempatch.git
    private_key: ((CLOUDFOUNDRY_STEMPATCH_DEPLOY_KEY))
    ignore_paths: [version/version]

- name: stemcell-builder-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))

- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))

- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: ((PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY))

- name: event-log-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/event-log-release.git
    private_key: ((EVENT_LOG_RELEASE_DEPLOY_KEY))

#releases

- name: stempatch-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: stempatch
    pre_release: true
    release: false
    drafts: true
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))

- name: event-log-release-github
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: event-log-release
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
    drafts: true

# time
- name: monthly-updates-trigger
  type: time
  source:
    interval: 720h

#files

- name: stempatch-untested-windows
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stempatch/untested/stempatch-windows-x86_64-(.*).exe
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

- name: stempatch-untested-linux
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stempatch/untested/stempatch-linux-x86_64-(.*)
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

- name: ovftool
  type: s3
  source:
    bucket: ((ROOT_BUCKET))
    regexp: stembuild/dependencies/VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

# locks
- name: vsphere-worker-lock
  type: pool
  source:
    branch: master
    pool: 'vsphere-worker-lock'
    private_key: ((BOSH-WINDOWS-LOCKS-CI_KEY))
    uri: git@github.com:pivotal-cf-experimental/Bosh-Windows-Locks

# versions
- name: stempatch-version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotal-cf/stempatch.git
    private_key: ((CLOUDFOUNDRY_STEMPATCH_DEPLOY_KEY))
    branch: master
    file: version/version
    initial_version: "0.3.6"

- name: updated-vmx-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: 2012R2/versions/vsphere-updated-vmx
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "1.0.0"

- name: event-log-release-version
  type: semver
  source:
    bucket: ((ROOT_BUCKET))
    key: event-log-release/version
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: "0.2.0"

jobs:

- name: build-stempatch
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: stempatch
        trigger: true
      - get: stempatch-version
  - put: stempatch-version
    params: {bump: patch}

- name: build-stempatch-windows
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: librsync
      - get: stempatch
        passed: [ build-stempatch ]
      - get: ci
      - get: stempatch-version
        passed: [ build-stempatch ]
        trigger: true
  - task: build
    tags: [vsphere-stembuild-worker]
    file: ci/tasks/build-stempatch-windows/task.yml
  - put: stempatch-untested-windows
    params:
      file: output/stempatch-windows-x86_64-*.exe

- name: build-stempatch-linux
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: librsync
      - get: stempatch
        passed: [ build-stempatch ]
      - get: ci
      - get: stempatch-version
        passed: [ build-stempatch ]
        trigger: true
      - get: ovftool
  - task: build
    file: ci/tasks/build-stempatch-linux/task.yml
  - put: stempatch-untested-linux
    params:
      file: output/stempatch-linux-x86_64-*

- name: bump-stemcell-builder-submodules
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: stemcell-builder-develop
      - get: bosh-agent
        trigger: true
      - get: bwats
        trigger: true
  - task: bump-submodules
    input_mapping:
      source-repo: stemcell-builder-develop
    output_mapping:
      bumped-repo: stemcell-builder-bumped
    file: ci/tasks/bump-submodules/task.yml
  - put: stemcell-builder-develop
    params:
      repository: stemcell-builder-bumped
      rebase: true

- name: create-vsphere-add-updates
  serial: true
  plan:
  - put: vsphere-worker-lock
    params:
      acquire: true
  - do:
    - in_parallel:
        fail_fast: true
        steps:
        - get: monthly-updates-trigger
          trigger: true
        - get: ci
        - get: stemcell-builder
        - get: windows-stemcell-dependencies
        - get: vmx-version
          resource: updated-vmx-version
    - task: add-updates
      privileged: true
      input_mapping: { version: vmx-version }
      file: ci/tasks/bosh-windows-stemcell-builder/create-vmx-add-updates/task.yml
      tags: [vsphere-windows-worker]
      params:
        OS_VERSION: windows2012R2
        ADMINISTRATOR_PASSWORD: "Password123!"
        AWS_ACCESS_KEY_ID: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
        AWS_REGION: us-east-1
        INPUT_BUCKET: "all-bosh-windows/2012R2/untested/vsphere/internal/inputs"
        OUTPUT_BUCKET: "all-bosh-windows/2012R2/untested/vsphere/internal/inputs"
    - put: updated-vmx-version
      params: {bump: major}
    ensure:
      put: vsphere-worker-lock
      params:
        release: vsphere-worker-lock

- name: post-stempatch-draft-release
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: stempatch-untested-windows
        passed: [ build-stempatch-windows ]
      - get: stempatch-untested-linux
        passed: [ build-stempatch-linux ]
      - get: stempatch-version
        passed: [ build-stempatch-linux, build-stempatch-windows ]
  - task: trim-version-from-binaries
    file: ci/tasks/set-stempatch-version/task.yml
  - put: stempatch-release
    params:
      name: output/tag
      tag: output/tag
      globs:
      - output/stempatch-*-x86_64-*
  - put: stempatch-version
    params: {bump: minor}

- name: test-stemcell-builder
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: stemcell-builder-develop
        trigger: true
      - get: stemcell-builder-master
        resource: stemcell-builder
  - in_parallel:
    - task: test-stemcell-builder
      file: ci/tasks/bosh-windows-stemcell-builder/rspec/task.yml
      input_mapping: {stemcell-builder: stemcell-builder-develop}
    - task: test-bosh-psmodules
      file: ci/tasks/bosh-windows-stemcell-builder/bosh-psmodules/task.yml
      input_mapping: {stemcell-builder: stemcell-builder-develop}
      tags:
      - vsphere-stembuild-worker
  - task: merge-to-master
    input_mapping: { from-repo: stemcell-builder-develop, to-repo: stemcell-builder-master }
    file: ci/tasks/merge-repo/task.yml
    params:
      FROM_BRANCH: develop
  - put: stemcell-builder
    params: { repository: merged-repo/to-repo }

- name: build-event-log-release
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: ci
      - get: event-log-release-version
        params:
          bump: minor
      - get: event-log-release
  - task: finalize-release
    file: ci/tasks/finalize-release/task.yml
    input_mapping:
      release: event-log-release
      version: event-log-release-version
    params:
      RELEASE_NAME: event-log
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: event-log-release
    params:
      repository: finalized-release/release
      tag: event-log-release-version/number
  - put: event-log-release-version
    params:
      file: event-log-release-version/number
  - put: event-log-release-github
    params:
      name: event-log-release-version/number
      tag: event-log-release-version/number
      globs:
      - finalized-release/event-log-*.tgz
