---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/ci },  }

inputs:
  - name: ci
  - name: stembuild-untested-linux
  - name: build-number
  - name: stemcell-build-number

outputs:
  - name: stembuild-built-stemcell

run:
  path: ci/tasks/stembuild-package/run.sh

params:
  VCENTER_BASE_URL:
  VCENTER_CA_CERT:
  VCENTER_USERNAME:
  VCENTER_PASSWORD:
  STEMBUILD_BASE_VM_NAME:
  VCENTER_VM_FOLDER: