---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: stemcell-builder
  - name: version
  - name: amis
  - name: default-stemcell

outputs:
  - name: copied-regional-stemcells

run:
  path: ci/tasks/bosh-windows-stemcell-builder/copy-aws-stemcell/run

params:
  OS_VERSION:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  REGIONS:
  VERSION_DIR: ../version
  AMIS_DIR:
  DEFAULT_STEMCELL_DIR: ../default-stemcell

