---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci
- name: release
- name: version

outputs:
- name: release-tarball

run:
  path: ci/tasks/bosh-cr/run
