---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: vsphere-stemcell-release-candidate
  - name: aws-stemcell-release-candidate
  - name: gcp-stemcell-release-candidate
  - name: azure-stemcell-release-candidate

run:
  path: ci/tasks/match-stemcell-versions/run
