---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: vsphere-stemcell-release-candidate
  - name: gcp-tested
  - name: azure-tested
  - name: stembuild-untested-linux
  - name: stembuild-untested-windows

run:
  path: ci/tasks/match-stemcell-versions/run
