---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: stemcell-builder
  - name: base-amis
  - name: version
  - name: windows-stemcell-dependencies
  - name: sshd
  - name: packer-ci-private-key

run:
  path: ci/tasks/bosh-windows-stemcell-builder/validate-packer-output-ami/run

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  AWS_REGION:

  VERSION_DIR: ../version
  AMIS_DIR: ../amis
