---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/govc } }

inputs:
  - name: ci

outputs:
  - name: hotfix-log

run:
  path: ci/tasks/install-windows-updates/run.sh

params:
  CREDENTIAL_URL:
  STEMBUILD_CONSTRUCT_TARGET_VM:
  VM_USERNAME:
  VM_PASSWORD:
