---
image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

platform: linux

inputs:
- name: ci
- name: app
- name: cfbench
  path: src/github.com/teddyking/cfbench

params:
  CF_API:
  CF_STACK:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_TAG:
  APP_DIR:
  APP_BUILDPACK:
  APP_START_COMMAND:
  DATADOG_API_KEY:
  DATADOG_APPLICATION_KEY:

run:
  path: ci/tasks/cfbench/run
