---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
  - name: ci
  - name: stembuild
outputs:
  - name: pivnet-metadata
run:
  path: ci/tasks/pivnet-stembuild-upload/run
params:
  OS_NAME:

