---
platform: windows

inputs:
  - name: ci
  - name: bosh-psmodules-repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-Command"
  - ci/tasks/test-units-bosh-psmodules/run.ps1
