---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: version
  - name: stemcell-builder
  - name: azure-base-vhd-uri

run:
  path: ci/tasks/print-azure-publishing-instructions/run

params:
  AZURE_CLIENT_ID: ((AZURE_CLIENT_ID))
  AZURE_CLIENT_SECRET: ((AZURE_CLIENT_SECRET))
  AZURE_STORAGE_ACCESS_KEY: ((AZURE_STORAGE_ACCESS_KEY))
  AZURE_STORAGE_ACCOUNT: ((AZURE_STORAGE_ACCOUNT))
  AZURE_PUBLISHED_STORAGE_ACCESS_KEY: ((AZURE_PUBLISHED_STORAGE_ACCESS_KEY))
  AZURE_PUBLISHED_STORAGE_ACCOUNT: ((AZURE_PUBLISHED_STORAGE_ACCOUNT))
  AZURE_TENANT_ID: ((AZURE_TENANT_ID))
  AZURE_CONTAINER_NAME: ((AZURE_CONTAINER_NAME))
  SKU: ((AZURE_SKU))
  PARTNER_PORTAL_TENANT_ID: ((PARTNER_PORTAL_TENANT_ID)) 
  PARTNER_PORTAL_CLIENT_ID: ((PARTNER_PORTAL_TENANT_ID)) 
  PARTNER_PORTAL_CLIENT_SECRET: ((PARTNER_PORTAL_TENANT_ID)) 

