---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: source-repo
- name: module-repo

outputs:
- name: bumped-repo

run:
  path: ci/tasks/bump-submodule/run

params:
  SUBMODULE:
