---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
  - name: ci
  - name: stembuild-untested-linux
  - name: stembuild-untested-windows
  - name: pivnet-release
  - name: version
outputs:
  - name: pivnet-metadata
run:
  path: ci/tasks/stembuild-prepare-pivnet-upload/run
params:
  OS_NAME:
