---
platform: windows

inputs:
- name: stembuild
- name: ci

run:
  path: powershell
  args:
  - "-File"
  - ci/tasks/stembuild/windows/contract/run.ps1

params:
  GOVC_INSECURE: 1
  GOVC_URL:
  VM_FOLDER:
  PACKAGE_TEST_BASE_VM_NAME:
