---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: downstream-release
  - name: upstream-release
  - name: ci

run:
  path: ci/tasks/sync-submodules/run

outputs:
- name: bumped-downstream-release
