---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: stemcell-automation
  - name: open-ssh
  - name: stemcell-builder
  - name: deps-file

outputs:
  - name: zip-file

run:
  path: ci/tasks/bosh-windows-stemcell-automation/package/zip-files.bash

params: []
