---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: stembuild
  - name: open-ssh
  - name: lgpo-binary
  - name: version
  - name: bosh-agent
  - name: bosh-psmodules

outputs:
  - name: deps-file

run:
  path: ci/tasks/generate-deps-file/run.bash

params:
