---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: librsync
  - name: stembuild
  - name: ci
  - name: stembuild-version
  - name: ovftool

run:
  path: /bin/bash
  args:
    - -c
    - ci/tasks/stembuild/linux/unit/run.sh
